### ISSUE TITLE
How to share data between main App and widget?

### ISSUE THREAD

**Issue by kesha-antonov** [matejkriz/react-native-today-widget#10]
Hello!

I'm trying to share data as you do in "Complex example". But with https://github.com/kevinresol/react-native-default-preference

Have you been able to use ```UserDefaults``` to share data?

### Description
In main app:
```
await DefaultPreference.setName("NAME_OF_YOUR_GROUP")
await DefaultPreference.set("key1", "value1")
```
In widget:
```
await DefaultPreference.setName("NAME_OF_YOUR_GROUP")
const k = await DefaultPreference.get("key1")
```
k is ```undefined```. Should be ```value1```

**Comment by kesha-antonov** [comment]
<img width="465" alt="screen shot 2017-12-31 at 00 01 52" src="https://user-images.githubusercontent.com/11584712/34457312-dfb36518-edbd-11e7-909b-8ace0f533115.png">

**Comment by matejkriz** [comment]
Hi, I have it on my [TODO list](https://github.com/matejkriz/react-native-today-widget#todo). 

Even with App Group defined without any errors, it doesn't work for me. Always `undefined`.

P.S.: You could use Setting API from React Native to use `UserDefaults `:  https://facebook.github.io/react-native/docs/settings.html

**Comment by sanjeev-sharma** [comment]
@matejkriz Just wanted to check in if you figured out the way to share data b/w app and today widget?

**Comment by sanjeev-sharma** [comment]
@kesha-antonov @matejkriz Just so you know I was able to figure out a way to share data b/w app and today widget. I will make a pull request soon to add an example under Examples

**Comment by matejkriz** [comment]
@kesha-antonov Wow, that's great, I'm really looking forward to that pull request!

**Comment by kesha-antonov** [comment]
@matejkriz I think you pinged wrong person ;)

@sanjeev-sharma can make that PR

**Comment by matejkriz** [comment]
Oh, sorry! Thanks for noticing 👍

**Comment by chuongle** [comment]
@sanjeev-sharma Can you please post your solution to share data between app and today widget?

**Comment by munsifhayat** [comment]
@sanjeev-sharma  any luck on that ?

**Comment by sanjeev-sharma** [comment]
@munsifhayat I am sorry. I never got the chance to complete this. I had made it work for my demo project but then I couldn't continue. I will try to locate those codes and will complete what I started but I am afraid it may take some time.

**Comment by munsifhayat** [comment]
@sanjeev-sharma No worries. I spent sometime. I have found some useful solutions too. You are always welcome and will feel happy to share my findings with you. (Y)
