### ISSUE TITLE
Instalation error: Could not write domain /../ios/TodayWidgetExtension/Info.plist;

### ISSUE THREAD

**Issue by josianeReis** [matejkriz/react-native-today-widget#11]
Hello;

I'm trying to install the react-native-today-widget in version 0.6.4 because of the react-native version of my project (0.44.3), I'm having this problem when I try to install the package:

```
yarn add react-native-today-widget@0.6.4
yarn add v0.24.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⡀ react-native-today-widget: setting ".TodayWidgetExtension" as CFBundleIdentifier for
/../ios/TodayWidgetEx
[-/1] ⡀ waiting...
[-/1] ⡀ waiting...
[-/1] ⡀ waiting...
error /Users/algartelecom/Documents/Josiane/testTodayWidget/node_modules/react-native-today-widget: Command failed.
Exit code: 1
Command: sh
Arguments: -c ./bin/setBundleId.sh
Directory: /Users/algartelecom/Documents/Josiane/testTodayWidget/node_modules/react-native-today-widget
Output:
./bin/setBundleId.sh: line 3: realpath: command not found
usage: dirname path
sed: 1: "s/^\s*"name": "(.*?)",$ ...": RE error: repetition-operator operand invalid
Reading CFBundleIdentifier from: /../../../ios//Info.plist
2018-01-08 16:46:09.080 defaults[13479:375454]
The domain/default pair of (/../../../ios//Info.plist, CFBundleIdentifier) does not exist
setting ".TodayWidgetExtension" as CFBundleIdentifier for  /../ios/TodayWidgetExtension/Info.plist
2018-01-08 16:46:09.219 defaults[13489:375499] Could not write domain /../ios/TodayWidgetExtension/Info.plist; exiting
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
``` 

Assuming I can not update the version of my project, what can I do to fix this?

Project Version: react-native 0.44.3
Version of react-native-today-widget: 0.6.4

Thanks!

**Comment by matejkriz** [comment]
Hi, `react-native-today-widget` 0.6.4   needs `realpath` from `coreutils`. Try to install it:
```
brew install coreutils
```

**Comment by matejkriz** [comment]
Could you find the library `react-native-today-widget` in the `/node_modules` even with this error during installation? If yes, you could run the falling script manually and provide your Bundle Identifier (you could find/set it in `./ios/testTodayWidget/Info.plist` file as `CFBundleIdentifier` ):
```
./node_modules/.bin/bundle-id {your bundle ID, e.g. org.reactjs.native.example.testTodayWidget}
```

**Comment by josianeReis** [comment]
Hi, thanks for the help.
After installing `coreutils` I was able to install the version `0.6.4` successfully, but when I do the application build I got this error: 


`error: Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.


		Embedded Binary Bundle Identifier:	.TodayWidgetExtension

		Parent App Bundle Identifier:		org.reactjs.native.example.testTodayWidget





** BUILD FAILED **



The following build commands failed:
	ValidateEmbeddedBinary build/Build/Products/Debug-iphonesimulator/testTodayWidget.app/PlugIns/TodayWidgetExtension.appex
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/testTodayWidget.app
An error was encountered processing the command (domain=IXErrorDomain, code=2):
Failed to set plugin placeholders for org.reactjs.native.example.testTodayWidget
Launching org.reactjs.native.example.testTodayWidget
org.reactjs.native.example.testTodayWidget: -1
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "org.reactjs.native.example.testTodayWidget" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "org.reactjs.native.example.testTodayWidget" is unknown to FrontBoard").`

Is it some other configuration I should do?

**Comment by matejkriz** [comment]
Try to run this command:
`./node_modules/.bin/bundle-id org.reactjs.native.example.testTodayWidget.TodayWidgetExtension`

or just reinstall node_modules:
`rm -rf node_modules && yarn`

**Comment by josianeReis** [comment]
Tks, It works. Do you know if there is any other way to fix this error without having to change the Bundle id?

**Comment by matejkriz** [comment]
It's not about changing the Bundle ID but it has to be set for the widget project and it has to start with Bundle ID of the main app (containing the widget).

This library runs[ the script to set Bundle ID](https://github.com/matejkriz/react-native-today-widget/blob/master/bin/setBundleId.rb) for the widget project [automatically after installation](https://github.com/matejkriz/react-native-today-widget/blob/master/package.json#L24).
