### ISSUE TITLE
Cannot get basic example to display widget

### ISSUE THREAD

**Issue by jeffreymendez1993** [matejkriz/react-native-today-widget#18]
### Description
Please describe expected and actual behavior.
Following steps from example app.
### System configuration
Please add result of `react-native info` command and `react-native-today-widget` version used
latest rn version and used npm install from master branch. 
<img width="270" alt="screen shot 2018-05-01 at 8 54 53 am" src="https://user-images.githubusercontent.com/8095978/39473563-702fb8d0-4d1d-11e8-9909-74fc92131f76.png">

**Comment by jeffreymendez1993** [comment]
I am not using react-native-fetch-blob as that is not stated in the installation docs.

**Comment by hjbaek** [comment]
same here

**Comment by elliscwc** [comment]
I'm also could not get it to show, any solution?
```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3
```

**Comment by elliscwc** [comment]
@matejkriz could you update and increase the version at yarn? thanks for the work 👍

**Comment by matejkriz** [comment]
@jeffreymendez1993 @hjbaek @elliscwc please try it with new `1.0.0` version and let me know if the issue has not been solved.

**Comment by jeffreymendez1993** [comment]
@matejkriz works you should also updated it. Looks like the content only shows if flex:1 is on the container.
