### ISSUE TITLE
Issue opening app by clicking widget Component

### ISSUE THREAD

**Issue by asadurrehmaan** [matejkriz/react-native-today-widget#28]
### Description
I have implemented this widget by following this example [Building a React-Native Today Widget in iOS](https://medium.com/@maximtoyberman/building-a-react-native-today-widget-in-ios-102830825e42)
I want to link a view to component in widget(icon) etc. When click that item it should open app and goto that screen.
But I don't know how to do it.
This code is working fine and showing images in widget except of opening app.

This is the code of my **index.widget.js** file

```
import React from 'react'
import {AppRegistry, Platform, Text, View, Image, TouchableOpacity, Linking} from 'react-native'
openMe = async (pm) => {
    console.warn(pm)
    Linking.openURL('appName://Camera/0')
}
const TodayWidget = () => (
<View style={{ flex: 1, flexDirection:'row', justifyContent: 'center',alignItems:'center'}}>
    <View style={{flex:1, justifyContent:'center',alignItems:'center'}}>
        <TouchableOpacity  onPress={() => this.openMe('first')}>
            <Image source={require('./app/Images/camera.png')} resizeMode='contain' style={{width:50,height:50}} />
        </TouchableOpacity>
    </View>

    <View style={{flex:1, justifyContent:'center',alignItems:'center'}}>
        <TouchableOpacity  onPress={() => this.openMe('second')}>
            <Image source={require('./app/Images/camera.png')} resizeMode='contain' style={{width:50,height:50}}/>
        </TouchableOpacity>
    </View>
</View>
)
if (Platform.OS === 'ios') {
AppRegistry.registerComponent('AITodayWidget', () => TodayWidget)
}
```

### Steps to reproduce
Please follow this example [Building a React-Native Today Widget in iOS ](https://medium.com/@maximtoyberman/building-a-react-native-today-widget-in-ios-102830825e42)
### System configuration
  OS: macOS High Sierra 10.13.6
  Node: 9.6.1
  Yarn: 0.15.1
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.52.0 => 0.52.3

**Comment by asadurrehmaan** [comment]
@matejkriz can you please help me in this issue?

**Comment by matejkriz** [comment]
Hi, you can't use `Linking` from `react-native` for that. You have to use `openURL` from (native) `widgetContext`. Here is the native module for it: https://github.com/matejkriz/react-native-today-widget/blob/master/ios/TodayWidgetExtension/Linking.m

So in `react-native-today-widget` you could use it like this: https://github.com/matejkriz/react-native-today-widget/blob/master/Examples/Complex/lib/openInApp.js
