### ISSUE TITLE
Failed to build iOS project.

### ISSUE THREAD

**Issue by RyanLiu0235** [matejkriz/react-native-today-widget#35]
### Description
I was just following the steps in `/Example/Basic` and nothing else. I added `react-native-today-widget` and run `react-native link`. Then `TodayWidget.js` and `index.widget.js`. At last, I run `react-native run-ios`, and then it said `failed to build ios project`.
<img width="640" alt="屏幕快照 2019-06-30 下午10 38 25" src="https://user-images.githubusercontent.com/5373041/60398214-5c6cc300-9b88-11e9-9162-3110f40a2559.png">

### Steps to reproduce
Just steps above.

### System configuration
I'm using `react-native-today-widget@1.0.0`. 

Results of `react-native info`:
```
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 145.09 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.6.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

**Comment by mavenai** [comment]
have you resolved this issue

**Comment by RyanLiu0235** [comment]
@mavenai Yes, I did. The truth is you can't build your own TodayWidget with this module alone. There is still something you have to do in xCode. You may get detailed steps with google.
