### ISSUE TITLE
Xcode Crash after linking

### ISSUE THREAD

**Issue by joncursi** [matejkriz/react-native-today-widget#4]
```
native-today-widget/ios/../../react-native/packager/react-native-xcode.sh: No such file or directory
```

![screen shot 2017-07-10 at 5 19 25 pm](https://user-images.githubusercontent.com/4974609/28040487-f14d1088-6593-11e7-89c8-6ecb58037bf9.png)

**Comment by matejkriz** [comment]
Thanks for info. I will look on it later this week. It looks like in RN 0.46 `react-native-xcode.sh` is moved to 'scripts' folder.

**Comment by matejkriz** [comment]
fixed in https://github.com/matejkriz/react-native-today-widget/pull/6
