### ISSUE TITLE
[error] react-native link Package name not found in {app-folder}/android/app/src/debug/AndroidManifest.xml

### ISSUE THREAD

**Issue by rodrigopk** [matejkriz/react-native-today-widget#9]
I've been receiving this error when I try to use `react-native link` command after installing.
```
rnpm-install ERR! ERRPACKAGEJSON No package found. Are you sure this is a React Native project?

Package name not found in {app-folder}/android/app/src/debug/AndroidManifest.xml
```
**react-native-cl version**: 2.0.1
**react-native version**: 0.47.2
**npm version** - 5.3.0
**yarn version** - 0.28.4

In the case that this is indeed a bug and not a misconfiguration of my part, how should I do the manual instalation of the extension in the lib? I've tried to do it using the scripts contained in the bin folder, but so far I could not get it right.

**Comment by matejkriz** [comment]
It doesn't seem like a problem with linking react-native-today-widget. There is no android part at all. Do you see in logs the beginning of linking this library?  (`rnpm-install info Linking react-native-today-widget ios dependency`)

The `./node_modules/.bin/embed-extension` script works only after linking.
You could try to follow the general process of manual linking: https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking
- file for step 1 is `/node_modules/react-native-today-widget/ios/RNTodayWidgetExtension.xcodeproj` 
- skip step 2, there is no static library, the TodayWidgetExtension.appex product will be linked by the script later
- in step 3, add `$(SRCROOT)/../node_modules/react-native-today-widget/ios/TodayWidgetExtension` to Header Sear Paths

After this process, you could run `./node_modules/.bin/embed-extension` script.

**Comment by rodrigopk** [comment]
Thanks for the fast reply @matejkriz.
Did some more digging, and the linking error may be related to [a problem with react-native-cli](https://github.com/facebook/react-native/issues/12216) 

I tried following your instructions to do the manual linking, but after running the `EmbendExtension.rb` script XCode (9.0.1) crashes with the following assertion error:
```
ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-13204/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/DataModel/References/PBXReference.m:242
Details:  (group) should not be nil.
```
Taking a look on my `project.pbxproj` file for the changes made by the script, I stumbled upon what seems to be a repeated entry of the extension on the `PBXReferenceProxy` section:

```
		54D1FE13B83CFE1CE408D9FB /* TodayWidgetExtension.appex */ = {
			isa = PBXReferenceProxy;
			fileType = "wrapper.app-extension";
			path = TodayWidgetExtension.appex;
			remoteRef = 2AEE843F35A195FD836C7330 /* PBXContainerItemProxy */;
			sourceTree = BUILT_PRODUCTS_DIR;
		};
		  .
                  .
                  .
		7FEFB6101FACBF9B00B7A62E /* TodayWidgetExtension.appex */ = {
			isa = PBXReferenceProxy;
			fileType = "wrapper.app-extension";
			path = TodayWidgetExtension.appex;
			remoteRef = 7FEFB60F1FACBF9B00B7A62E /* PBXContainerItemProxy */;
			sourceTree = BUILT_PRODUCTS_DIR;
		};
```
Removing the second entry would stop XCode from crashing, but the extension would not be installed on the simulator when running the app. Removing the first one would cause XCode to crash on launch with the previous error message.

Any ideas on what I'm doing wrong?

**Comment by matejkriz** [comment]
I don't know how to investigate what is wrong, but you could link it fully manually. 
- start from scratch (`rm -rf node_modules/react-native-today-widget && yarn`)
- follow again the manual linking guide, but at this time as a step 2, add `TodayWidgetExtension.appex` to Embedded Binaries on the General tab for your main target.
- do not run the embed-extension at all, just `reat-native run-ios` after step 3
<img width="1001" alt="screen shot 2017-11-03 at 17 55 11" src="https://user-images.githubusercontent.com/3729633/32386154-983ffc02-c0c0-11e7-8279-4fa3f1250cd5.png">

I just tried it with react-native@0.47.2 and react-native-today-widget@0.7.1 and it works.

**Comment by matejkriz** [comment]
To document manual linking clearly is on my TODO list (https://github.com/matejkriz/react-native-today-widget#todo).

**Comment by matejkriz** [comment]
@rodrigopk Please let me know if it works for you, so I could close this issue.

**Comment by matejkriz** [comment]
No update, so closing the issue. Let me know if it is still valid.

**Comment by muzammil-triffort** [comment]
I run `react-native upgrade` and updated all default files for Android. After that it works fine.

**Comment by ChandniSharma** [comment]
I tried it and upgraded it getting this message 
Successfully upgraded this project to react-native v0.57.3
but after that when I run again link command getting error.

**Comment by rickcha** [comment]
I had the same error but resolved by looking inside AndroidManifest.xml. The package name was missing inside the manifest tag.

**Comment by HarshitMadhav** [comment]
Cleaning the gradle for the project worked for me.

**Comment by quangcanh2975** [comment]
> I run `react-native upgrade` and updated all default files for Android. After that it works fine.

@muzammil-triffort It worked for me. Thank you so much !
